//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuOptions
    {
        public int idOption { get; set; }
        public string NameSpace { get; set; }
        public string NomClase { get; set; }
        public string NomDLL { get; set; }
        public string NomPanel { get; set; }
        public string RangMin { get; set; }
        public string Text { get; set; }
        public string Picture { get; set; }
    }
}
