//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public short idOrderInfo { get; set; }
        public short idOrder { get; set; }
        public short idAgency { get; set; }
        public short idOperationalArea { get; set; }
    
        public virtual Agencies Agencies { get; set; }
        public virtual OperationalAreas OperationalAreas { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
