//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class securecoreEntities : DbContext
    {
        public securecoreEntities()
            : base("name=securecoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DefinedRoutes> DefinedRoutes { get; set; }
        public virtual DbSet<Factories> Factories { get; set; }
        public virtual DbSet<Filiations> Filiations { get; set; }
        public virtual DbSet<MenuOptions> MenuOptions { get; set; }
        public virtual DbSet<MilitaryCamps> MilitaryCamps { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersDetail> OrdersDetail { get; set; }
        public virtual DbSet<PlanetRoutes> PlanetRoutes { get; set; }
        public virtual DbSet<Planets> Planets { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<References> References { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<RouteTypes> RouteTypes { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<SpaceShipCategories> SpaceShipCategories { get; set; }
        public virtual DbSet<SpaceShips> SpaceShips { get; set; }
        public virtual DbSet<SpaceShipTypes> SpaceShipTypes { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserCategories> UserCategories { get; set; }
        public virtual DbSet<UserRanks> UserRanks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
