//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasDiarias
    {
        public int idTareaDiaria { get; set; }
        public int idUser { get; set; }
        public System.DateTime fecha { get; set; }
        public string Tarea { get; set; }
        public string Titulo { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
