//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordinateKeys
    {
        public int idCoordinateKey { get; set; }
        public int idInnerEncryption { get; set; }
        public string Coordinate { get; set; }
        public string CoordinateKey { get; set; }
    
        public virtual InnerEncryption InnerEncryption { get; set; }
    }
}
