//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinedRoutes
    {
        public int idDefinedRoute { get; set; }
        public Nullable<int> idPlanetOri { get; set; }
        public Nullable<int> idPlanetDest { get; set; }
        public Nullable<int> idRoute { get; set; }
        public string RouteMap { get; set; }
    
        public virtual Routes Routes { get; set; }
    }
}
