//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanetRoutes
    {
        public int idPlanetRoute { get; set; }
        public Nullable<int> idPlanet { get; set; }
        public Nullable<int> idRoute { get; set; }
    
        public virtual Planets Planets { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
