//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanetKeys
    {
        public int idKey { get; set; }
        public int idPlanet { get; set; }
        public string XMLKey { get; set; }
    
        public virtual Planets Planets { get; set; }
    }
}
