//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceShipTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpaceShipTypes()
        {
            this.SpaceShips = new HashSet<SpaceShips>();
        }
    
        public int idSpaceShipType { get; set; }
        public string CodeSpaceShipType { get; set; }
        public string DescSpaceShipType { get; set; }
        public Nullable<int> idFiliation { get; set; }
        public Nullable<int> idSpaceShipCategory { get; set; }
    
        public virtual Filiations Filiations { get; set; }
        public virtual SpaceShipCategories SpaceShipCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpaceShips> SpaceShips { get; set; }
    }
}
